# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HagenDev
email: casey@hagendev.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website/portfolio. Look forward to possibly blogging
  stuff I learn about and my feelings. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hagendev.com" # the base hostname & protocol for your site
twitter_username: aechagen
github_username:  aechagen

# Build settings
markdown: kramdown
